#!/bin/bash

set -e

source /usr/local/rvm/scripts/rvm
cd /var/www/$APP_NAME
bundle install

if ! gem spec passenger > /dev/null 2>&1; then 
  gem install passenger
fi

bundle exec rake db:create
bundle exec rake db:schema:load
bundle exec rake db:seed

passenger start -p 80 -e $RAILS_ENV
