#!/bin/bash

set -e

source /usr/local/rvm/scripts/rvm
cd /var/www/$APP_NAME

gem install json -v '1.8.1'

bundle install

bundle exec rake db:create
bundle exec rake db:schema:load
bundle exec rake db:seed

rails s Puma -e development -p 3000
